//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseType
    {
        public int HouseTypeId { get; set; }
        public string HouseType1 { get; set; }
    }
}
